name: Encrypt and Commit GSocket Install Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  encrypt_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install prerequisites
        run: sudo apt install openssl && openssl version && uname -a && cd ${{ GitHub.workspace }}

      - name: Download GSocket Install Script
        run: wget -O gsocket-install.sh https://gsocket.io/y

      - name: Download BinCrypter
        run: wget -O bincrypter.sh https://raw.githubusercontent.com/hackerschoice/bincrypter/refs/heads/main/bincrypter.sh

      - name: Set execute permissions on BinCrypter
        run: chmod +x bincrypter.sh

      - name: Verify the scripts
        run: md5sum gsocket-install.sh bincrypter.sh

      - name: Encrypt GSocket Install Script
        run: ./bincrypter.sh gsocket-install.sh

      - name: Test run
        run: . ./gsocket-install.sh        

      - name: Commit encrypted script
        run: |
          git add gsocket-install.sh
          git commit -m "Add encrypted gsocket-install.sh"
          git push
